/*
 * Copyright (c) 2023. Bear Giles <bgiles@coyotesong.com>.
 * All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.coyotesong.microservice.rss.model.matchers;

import com.coyotesong.microservice.rss.model.FeedHeader;
import org.hamcrest.Description;
import org.hamcrest.Matcher;
import org.hamcrest.TypeSafeMatcher;
import org.hamcrest.core.IsEqual;
import org.hamcrest.core.IsNull;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Hamcrest Matcher for FeedHeader objects
 * <p>
 * This file was autogenerated.
 * </p>
 */
public class FeedHeaderMatcher extends TypeSafeMatcher<FeedHeader> {
    private final Map<String, Matcher<?>> matchers = new LinkedHashMap<>();
    private final List<String> expectedContent = new ArrayList<>();
    private final FeedHeader expected;

    /**
     * Define the matchers that will perform the actual tests
     */
    public FeedHeaderMatcher(FeedHeader expected) {
        this.expected = expected;

        if (expected.getValue() != null) {
            matchers.put("value", IsEqual.equalTo(expected.getValue()));
        } else {
            matchers.put("value", IsNull.nullValue());
        }

        expectedContent.add("value: " + expected.getValue());
    }

    /**
     * Describe the expected value
     */
    @Override
    public void describeTo(Description description) {
        description.appendValueList("FeedHeader: [ ", ", ", " ]", expectedContent);
    }

    /**
     * Describe difference between actual and expected values
     */
    @Override
    public void describeMismatchSafely(FeedHeader actual, Description description) {
        final List<String> actualContent = new ArrayList<>();

        if (!matchers.get("value").matches(actual.getValue())) {
            actualContent.add("value: " + actual.getValue());
        }

        if (!actualContent.isEmpty()) {
            description.appendValueList("FeedHeader [ ", ", ", " ]", actualContent);
        }
    }

    /**
     * Determine the differences between the expected and actual values.
     */
    @Override
    protected boolean matchesSafely(FeedHeader actual) {
        if (!matchers.get("value").matches(actual.getValue())) {
            return false;
        }

        return true;
    }

    /**
     * Static factory
     *
     * @param expected
     */
    public static FeedHeaderMatcher equalTo(FeedHeader expected) {
        return new FeedHeaderMatcher(expected);
    }

    /**
     * Static factory
     *
     * @param expected
     */
    public static FeedHeaderMatcher deepEqualTo(FeedHeader expected) {
        throw new AssertionError("unimplemented method");
    }
}

