/*
 * Copyright (c) 2023. Bear Giles <bgiles@coyotesong.com>.
 * All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.coyotesong.microservice.rss.model.matchers;

import com.coyotesong.microservice.rss.model.WireFeed;
import org.hamcrest.Description;
import org.hamcrest.Matcher;
import org.hamcrest.TypeSafeMatcher;
import org.hamcrest.core.IsEqual;
import org.hamcrest.core.IsNull;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Hamcrest Matcher for WireFeed objects
 * <p>
 * This file was autogenerated.
 * </p>
 */
public class WireFeedMatcher extends TypeSafeMatcher<WireFeed> {
    private final Map<String, Matcher<?>> matchers = new LinkedHashMap<>();
    private final List<String> expectedContent = new ArrayList<>();
    private final WireFeed expected;

    /**
     * Define the matchers that will perform the actual tests
     */
    public WireFeedMatcher(WireFeed expected) {
        this.expected = expected;

        if (expected.getId() != null) {
            matchers.put("id", IsEqual.equalTo(expected.getId()));
        } else {
            matchers.put("id", IsNull.nullValue());
        }
        if (expected.getEncoding() != null) {
            matchers.put("encoding", IsEqual.equalTo(expected.getEncoding()));
        } else {
            matchers.put("encoding", IsNull.nullValue());
        }
        if (expected.getFeedType() != null) {
            matchers.put("feedType", IsEqual.equalTo(expected.getFeedType()));
        } else {
            matchers.put("feedType", IsNull.nullValue());
        }
        if (expected.getStylesheet() != null) {
            matchers.put("stylesheet", IsEqual.equalTo(expected.getStylesheet()));
        } else {
            matchers.put("stylesheet", IsNull.nullValue());
        }

        expectedContent.add("id: " + expected.getId());
        expectedContent.add("encoding: " + expected.getEncoding());
        expectedContent.add("feedType: " + expected.getFeedType());
        expectedContent.add("stylesheet: " + expected.getStylesheet());
    }

    /**
     * Describe the expected value
     */
    @Override
    public void describeTo(Description description) {
        description.appendValueList("WireFeed: [ ", ", ", " ]", expectedContent);
    }

    /**
     * Describe difference between actual and expected values
     */
    @Override
    public void describeMismatchSafely(WireFeed actual, Description description) {
        final List<String> actualContent = new ArrayList<>();

        if (!matchers.get("id").matches(actual.getId())) {
            actualContent.add("id: " + actual.getId());
        }
        if (!matchers.get("encoding").matches(actual.getEncoding())) {
            actualContent.add("encoding: " + actual.getEncoding());
        }
        if (!matchers.get("feedType").matches(actual.getFeedType())) {
            actualContent.add("feedType: " + actual.getFeedType());
        }
        if (!matchers.get("stylesheet").matches(actual.getStylesheet())) {
            actualContent.add("stylesheet: " + actual.getStylesheet());
        }

        if (!actualContent.isEmpty()) {
            description.appendValueList("WireFeed [ ", ", ", " ]", actualContent);
        }
    }

    /**
     * Determine the differences between the expected and actual values.
     */
    @Override
    protected boolean matchesSafely(WireFeed actual) {
        if (!matchers.get("id").matches(actual.getId())) {
            return false;
        }
        if (!matchers.get("encoding").matches(actual.getEncoding())) {
            return false;
        }
        if (!matchers.get("feedType").matches(actual.getFeedType())) {
            return false;
        }
        if (!matchers.get("stylesheet").matches(actual.getStylesheet())) {
            return false;
        }

        return true;
    }

    /**
     * Static factory
     *
     * @param expected
     */
    public static WireFeedMatcher equalTo(WireFeed expected) {
        return new WireFeedMatcher(expected);
    }

    /**
     * Static factory
     *
     * @param expected
     */
    public static WireFeedMatcher deepEqualTo(WireFeed expected) {
        throw new AssertionError("unimplemented method");
    }
}

